(async () => {
    var promise1 = new Promise(function(resolve, reject) {
        resolve('foo');
    });
    let myval="4";
    var thenedPromise = promise1.then(function(value) {
     myval=value;
      console.log(value); // this logs "foo"
    });

    thenedPromise; // wait before the promise generated by "then" is resolved

    console.log(myval); // logs "foo"
})();